project:
  type: website

website:
  title: "Jandersolutions"
  navbar:
    title: Datacado
    logo: images/logo.png
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: solar
    css: styles.css

editor: visual

