project:
  type: website
  output-dir: docs

website:
  title: "Janderscience"
  favicon: logo.png
  site-url: "https://jander.science"
  site-path: '/'
  twitter-card: true
  open-graph:
    locale: pt_BR
    site-name: janderscience
  google-analytics:
    tracking-id: "G-57EC9PE2WR"
    anonymize-ip: true
  cookie-consent:
    type: express
    style: headline
    palette: dark
    language: pt
  navbar:
    right:
      - Sobre.qmd
      - Datacado.qmd
      - Pythematica.qmd
      - Blog.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/janderson-abreu-1b4466106/
      - icon: github
        href: https://github.com/Jandersolutions
      - icon: whatsapp
        href: https://api.whatsapp.com/send?phone=5561981423845
      - icon: medium
        href: https://medium.com/@jandersonabreu5
format:
  html:
    theme: 
      light: minty
      dark: cyborg
    css: styles.css

editor: visual

